### ISSUE TITLE
Navigable Snapshots, Replay

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [SEPR-EEP/taxe-game-3#16]
- [X] Implement the `Snapshot` class, containing properties of the Game at a given point in time
- [X] Keep a list of snapshots in memory
- [X] Implement the method `Game.getSnapshotsNumber()` to know how many snapshots there are
- [X] Implement the method `Game.createSnapshot()` to push a snapshot of the current state to the list
- [X] Implement the method `Game.loadSnapshot(Snapshot)` to load a snapshot
- [X] Have the game create snapshots automatically when something happens
- [x] "Replay mode" flag to distinguish when replaying and when playing
- [x] Add replay methods to navigate between snapshots
- [x] Test snapshots 
- [x] Replay UI
- [ ] Optional. Save and load Snapshots list - integrated db or file

**Comment by AlfioEmanueleFresta** [comment]
While playing, snaphshots are created. The method that triggers the creation of a snapshot is `setState`. This happens every time a turn is ended, and at every start of an animation - so it is fine for a nice animated replay. At this time it is also triggered for minor events we may want to exclude (such as when you want to place a train and the cursors changes).

![image](https://cloud.githubusercontent.com/assets/621062/7105616/d1559bfc-e119-11e4-8f4c-9d96c3724f48.png)

**Comment by AlfioEmanueleFresta** [comment]
Something we could think about :
- [ ] Control replay speed using a speed factor. E.g 2x would double the speed of the train and divide in half the max animation  turn time 
- [ ] Change snapshots counter to percentage or simple progress bar
- [ ] Disable buttons and actions during replay mode

**Comment by rc1035** [comment]
Great progress so far! Few bugs spotted from a quick test run:
- If a train is destroyed by a disaster in normal mode, then in replay mode a null pointer exception will occur.
- Once the replay has finished a player cannot select any unplaced trains - a message will appear telling them they belong to their opponent.
- If you try to run the replay a 2nd time, or multiple times, (after the 1st replay has finished) all sorts of crazy things can happen.

**Comment by AlfioEmanueleFresta** [comment]
@rc1035 you're right, I'm pretty sure this is not supposed to happen:

![image](https://cloud.githubusercontent.com/assets/621062/7333596/951e6b92-eb6d-11e4-897d-56d1dcaf5713.png)

I'm trying to figure out the nature of the problem - unfortunately with no luck for now.

**Comment by AlfioEmanueleFresta** [comment]
Found the problem that caused trains to be unselectable after a replay.

The following code was used to check if a Train was stationary at a given station:

``` java
if(((Train) resource).getPosition() == station.getLocation()) {
```

In Java, the `==` operator returns true for objects only if the two sides are references to the same object, **not** if the two objects are considered equal (i.e. two different position objects -generated by cloning when a snapshot is created- that contain the same X and Y values were considered not equal). Fixed by changing the condition to:

``` java
if(((Train) resource).getPosition().equals(station.getLocation())) {
```

Very subtle indeed.

**Comment by AlfioEmanueleFresta** [comment]
These seem to be the major problems atm:
1. When replaying, the first train moves are always wrong. Instead of going from the first station towards the second, the train moves from the latest station reached towards the second of the route. Once the second station of the route has been reached, the route continues normally.
2. When replaying **if the replay has been started when the train is still moving**, crazy things happen. This seems mainly due to the fact that the train route is not cancelled and the actor is not told to stop. 
   - ATM the only solution I can think of would be not to allow the player to start a replay if a train is moving.

**Comment by rc1035** [comment]
That is a very subtle bug, not sure if I would have been able to spot it!

For the 1st problem, it sounds like issues possibly relating to (1) the position of the train, and/or (2) the order that which actions are added to the actor of the train. I'll look into it tomorrow.

For the 2nd problem, what do you mean by 'train is still moving' - does this mean the train has not yet reached the final destination of its route, or that the actor of the train is still moving (i.e. we are still in the animating state). I think not allowing the replay button to be pressed during the animating state is perfectly reasonable.

An additional bug:

Once a goal is completed we get a null pointer exception. The issue seems to be at TrainMoveController.java:113, we try to set the trains' actor's visibility to false, yet the train no longer has an actor.

**Comment by AlfioEmanueleFresta** [comment]
Apparently all of the problems up here have been solved now.
