### ISSUE TITLE
Trains at Junctions

### ISSUE THREAD

**Issue by kokoff** [SEPR-EEP/taxe-game-3#17]
When removing  connection part of a train's route should we allow the new route to end at a junction i.e. should a train be able to be positioned at a junction and not moving?

**Comment by rc1035** [comment]
If a train ends up being stationary at a junction, any train that passes it will crash - destroying both trains. We could just call this an extra "gameplay feature" if we wanted to! On one hand players might find it slightly annoying, on the other hand it encourages them to think more about the consequences of removing a connection.

**Comment by kokoff** [comment]
That's exactly what I was thinking but I could't decide what was better. Changing it is a matter of 2-3 lines of code so we just need to decide on something. Maybe we could discuss it in our next meeting.

**Comment by rc1035** [comment]
Sure we can do. Thinking about the real world, if somebody somehow removed the train tracks connected to a junction it does seem likely that a crash could occur. So we could argue this makes our game more realistic.
