### ISSUE TITLE
Bugs to be fixed

### ISSUE THREAD

**Issue by rc1035** [SEPR-EEP/taxe-game-3#19]
- [x] When removing a connection which is part of a train's route, it teleports to the next station in its route.
- [x] When replaying, goals disappear, and then randomly appear again.
- [x] When replay finises, a player is shown their opponents resources.
- [x] If doing a replay after modifying connections, these changes are not reverted. The map does not update - could be as easy as repainting the map.
- [x] After a collision or a disaster, the train's actor is destroyed - which means it cannot be replayed.

**Comment by AlfioEmanueleFresta** [comment]
- [x] Natural disasters do not clear when starting a replay
- [x] Natural disasters are not reproduced in the replay
- [x] Natural disasters destroy trains, breaking everything apart
