### ISSUE TITLE
Unit Test Errors

### ISSUE THREAD

**Issue by kokoff** [SEPR-EEP/taxe-game-3#4]
7 out of 15 unit tests throw errors when ran. All the errors occur when trying to access a file from assets folder.
- [x] Fix errors

**Comment by rc1035** [comment]
Non of the unit tests run for me in IntelliJ, I'm yet to get the configuration to work as it should. Have you had any better luck Alfio?

I managed to get the game running by moving the tests into its own src folder. At the moment it's contained within the same src folder as all the game code, which I don't think is ideal. Perhaps the tests have not been configured to work with Gradle as they're supposed to?

**Comment by kokoff** [comment]
JUnit library is currently not imported in the project for some reason. You have to import it to be able to run the tests.

**Comment by AlfioEmanueleFresta** [comment]
@rc1035 fixed. I also added the run configurations for building and running the project under intellij idea.
